project_name: env-lint

builds:
  - id: env-lint
    main: .
    binary: env-lint
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    builds: [env-lint]
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: chidinma21
    name: env-lint
